# Generated by Django 4.2 on 2023-04-30 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_updated_at_alter_task_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="date",
            new_name="created_at",
        ),
    ]
