# Generated by Django 4.2 on 2023-04-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_task_is_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="execute_at",
            field=models.DateTimeField(null=True),
        ),
    ]
